name: HomePod Connect
version: 28.6-ls105
slug: homepod-connect
description: Play Spotify music on your HomePods through Spotify Connect
arch:
  - aarch64
  - amd64
map:
  - config:rw
  - media:rw
host_network: true
host_dbus: false
host_ipc: false
hassio_api: false
auth_api: false
hassio_role: "default"
audio: false
init: false
startup: application
boot: auto
image: alexbabel/owntone
webui: http://[HOST]:[PORT:3689]
stage: experimental
url: https://community.home-assistant.io/t/homepod-connect-spotify-on-homepods-with-spotify-connect/482227
homeassistant: "0.110"
